replicaCount: 1

image:
  pullPolicy: Always

imagePullSecrets:
  - name: github-regcred

nameOverride: ""
fullnameOverride: "openissuer-site"

serviceAccount:
  create: false
  annotations: {}
  name:

podSecurityContext: {}

securityContext: {}

rbac:
  create: false

service:
  type: ClusterIP
  port: 80
  targetPort: 3000

istio:
  enabled: false

ingress:
  enabled: false

httproute:
  gatewayName: shared-tls-gateway
  namespace: main
  pathPrefix: /
  hostRoutes:
    - name: openissuer
      hostname: openissuer.com
      httpsListenerName: https-openissuer
      httpListenerName: http-openissuer
    - name: openissuer-www
      hostname: www.openissuer.com
      httpsListenerName: https-openissuer-www
      httpListenerName: http-openissuer-www

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

postgres:

autoscaling:
  enabled: false

envs: []

secretenvs: []

secretFiles: []

health:
  liveness:
    path: /
    port: 3000
    initialDelaySeconds: 20
    periodSeconds: 10
    failureThreshold: 5
  readiness:
    path: /
    port: 3000
    initialDelaySeconds: 10
    periodSeconds: 5
    failureThreshold: 5
